### ISSUE TITLE
🐛 [BUG] Content Security Policy error

### ISSUE THREAD

**Issue by nilooy** [samrum/create-vite-plugin-web-extension#11]
## First of all, thanks for this wonderful project. 🥇 

Generated with `npm init @samrum/vite-plugin-web-extension` and selected preact with no ts and manifest v3.

After running
```
npm run serve:chrome
```
Getting this error on extension page.

`Refused to load the script 'http://localhost:3000/@vite/client' because it violates the following Content Security Policy directive: "script-src 'self'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.`

<img width="817" alt="Screenshot 2022-03-28 at 00 22 01" src="https://user-images.githubusercontent.com/32486682/160295160-b1aa7600-3291-42bb-b220-03d6c18e1aba.png">

**Comment by samrum** [comment]
This is an issue with Chromium and manifest V3. There's an open issue here: https://bugs.chromium.org/p/chromium/issues/detail?id=1290188

It's mentioned in the README for [samrum/vite-plugin-web-extension](https://github.com/samrum/vite-plugin-web-extension):
`HMR support for all manifest properties (excluding Manifest V3)`
